spring:
  application:
    name: usuario
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083
springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger.html

---
spring.config.activate.on-profile: docker
server.port: 8080
spring.datasource.url: jdbc:postgresql://usuario-db:5432/mydatabase
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/