spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banco
    username: luiz
    password: 0609

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: app_topicos
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/topicos
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/topicos/protocol/openid-connect/certs

springdoc:
  api-docs:
    path: /api-doc/docs
  swagger-ui:
    path: /api-doc/swagger.html

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://backend-db:5432/topicos
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/topicos/protocol/openid-connect/certs
