# Spring Boot configuration
spring:
  application:
    name: arquivos
  datasource:
    url: jdbc:postgresql://localhost:5433/files-service
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# Server configuration
server:
  port: 8085
